CREATE DATABASE [Proyecto Sistemas Transaccionales SQL]

CREATE TABLE CIUDAD (
    id_ciudad INT NOT NULL IDENTITY(1,1),
    nombre VARCHAR(100) NOT NULL,
    CONSTRAINT PK_CIUDAD PRIMARY KEY (id_ciudad) 
);

CREATE TABLE SEDE (
    id_sede INT NOT NULL IDENTITY(1,1),
    id_ciudad INT NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    CONSTRAINT PK_SEDE PRIMARY KEY (id_sede),
    CONSTRAINT FK_SEDE_CIUDAD FOREIGN KEY (id_ciudad) REFERENCES CIUDAD (id_ciudad) ON UPDATE CASCADE
);

CREATE TABLE TIPO_DE_DOCUMENTO (
    id_tip_documento INT NOT NULL IDENTITY(1,1),
    descripcion VARCHAR(100) NOT NULL,
    CONSTRAINT PK_TIPO_DE_DOCUMENTO PRIMARY KEY (id_tip_documento)
);

CREATE TABLE ESTADO_DISPOSITIVO (
    id_estado INT NOT NULL IDENTITY(1,1),
    activo_inactivo BIT NOT NULL,
    CONSTRAINT PK_ESTADO_DISPOSITIVO PRIMARY KEY (id_estado)
);

CREATE TABLE TIPO_DISPOSITIVO (
    id_tip_dispo INT NOT NULL IDENTITY(1,1),
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255)  NULL,
    cantidad INT NOT NULL DEFAULT 0,
    CONSTRAINT PK_TIPO_DISPOSITIVO PRIMARY KEY (id_tip_dispo)
);

CREATE TABLE PROVEEDOR (
    id_proveedor INT NOT NULL IDENTITY(1,1),
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    coreo_electronico VARCHAR(150) NULL,
    telefono BIGINT NULL,
    CONSTRAINT PK_PROVEEDOR PRIMARY KEY (id_proveedor)
);

CREATE TABLE PROVEEDOR_TIPO_DISPOSITIVO (
    id_proveedor INT NOT NULL,
    id_tip_dispo INT NOT NULL,
    CONSTRAINT PK_PROV_TIPO_DISPO PRIMARY KEY (id_proveedor, id_tip_dispo),
    CONSTRAINT FK_PTD_PROVEEDOR   FOREIGN KEY (id_proveedor) REFERENCES PROVEEDOR (id_proveedor) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_PTD_TIPO_DISPO  FOREIGN KEY (id_tip_dispo) REFERENCES TIPO_DISPOSITIVO (id_tip_dispo) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE DISPOSITIVO (
    id_dispositivo INT NOT NULL IDENTITY(1,1),
    id_proveedor INT NOT NULL,
    id_estado INT NOT NULL,
    id_tip_dispo INT NOT NULL,
    serial VARCHAR(100) NOT NULL,
    CONSTRAINT PK_DISPOSITIVO PRIMARY KEY (id_dispositivo),
    CONSTRAINT UQ_DISPOSITIVO_SERIAL UNIQUE (serial),
    CONSTRAINT FK_DISP_PROVEEDOR FOREIGN KEY (id_proveedor) REFERENCES PROVEEDOR (id_proveedor),
    CONSTRAINT FK_DISP_ESTADO FOREIGN KEY (id_estado) REFERENCES ESTADO_DISPOSITIVO (id_estado),
    CONSTRAINT FK_DISP_TIPO FOREIGN KEY (id_tip_dispo) REFERENCES TIPO_DISPOSITIVO (id_tip_dispo)
);

CREATE TABLE MODALIDAD (
    id_modalidad INT NOT NULL IDENTITY(1,1),
    tipo_modalidad VARCHAR(100) NOT NULL,
    CONSTRAINT PK_MODALIDAD PRIMARY KEY (id_modalidad)
);

CREATE TABLE JORNADA (
    id_jornada INT NOT NULL IDENTITY(1,1),
    nombre_jornada VARCHAR(100) NOT NULL,
    CONSTRAINT PK_JORNADA PRIMARY KEY (id_jornada)
);

CREATE TABLE SEDE_MODALIDAD_JORNADA (
    id_sede INT NOT NULL,
    id_modalidad INT NOT NULL,
    id_jornada INT NOT NULL,
    CONSTRAINT PK_SEDE_MOD_JOR PRIMARY KEY (id_sede, id_modalidad, id_jornada),
    CONSTRAINT FK_SMJ_SEDE FOREIGN KEY (id_sede) REFERENCES SEDE (id_sede) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_SMJ_MODALIDAD FOREIGN KEY (id_modalidad) REFERENCES MODALIDAD (id_modalidad) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_SMJ_JORNADA   FOREIGN KEY (id_jornada) REFERENCES JORNADA (id_jornada) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE USUARIO (
    id_usuario INT NOT NULL IDENTITY(1,1),
    id_sede INT NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    id_tip_documento INT NOT NULL,
    num_documento BIGINT NOT NULL,
    coreo_electronico VARCHAR(150) NULL,
    telefono BIGINT NULL,
    CONSTRAINT PK_USUARIO PRIMARY KEY (id_usuario),
    CONSTRAINT UQ_USUARIO_DOC UNIQUE (id_tip_documento, num_documento),
    CONSTRAINT FK_USU_SEDE FOREIGN KEY (id_sede) REFERENCES SEDE (id_sede),
    CONSTRAINT FK_USU_TIPO_DOC FOREIGN KEY (id_tip_documento) REFERENCES TIPO_DE_DOCUMENTO (id_tip_documento)
);

CREATE TABLE METODO_PAGO (
    id_metodo INT NOT NULL IDENTITY(1,1),
    descripcion VARCHAR(100) NOT NULL,
    CONSTRAINT PK_METODO_PAGO PRIMARY KEY (id_metodo)
);

CREATE TABLE PRESTAMO (
    id_prestamo INT NOT NULL IDENTITY(1,1),
    id_usuario  INT NOT NULL,
    fecha_inicio DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_PRESTAMO PRIMARY KEY (id_prestamo),
    CONSTRAINT FK_PREST_USUARIO FOREIGN KEY (id_usuario) REFERENCES USUARIO (id_usuario)
);

CREATE TABLE DETALLE_PRESTAMO (
    id_detalle INT NOT NULL IDENTITY(1,1),
    id_prestamo INT NOT NULL,
    id_dispositivo INT NOT NULL,
    valor DECIMAL(18,2) NOT NULL,
    CONSTRAINT PK_DETALLE_PRESTAMO PRIMARY KEY (id_detalle),
    CONSTRAINT UQ_DETALLE_PREST_DISP UNIQUE (id_prestamo, id_dispositivo),
    CONSTRAINT FK_DET_PRESTAMO FOREIGN KEY (id_prestamo) REFERENCES PRESTAMO (id_prestamo),
    CONSTRAINT FK_DET_DISPOSITIVO   FOREIGN KEY (id_dispositivo) REFERENCES DISPOSITIVO (id_dispositivo)
);

CREATE TABLE PAGO (
    id_pago INT NOT NULL IDENTITY(1,1),
    id_prestamo INT NOT NULL,
    id_metodo INT NOT NULL,
    monto DECIMAL(18,2) NOT NULL,
    CONSTRAINT PK_PAGO PRIMARY KEY (id_pago),
    CONSTRAINT FK_PAGO_PRESTAMO FOREIGN KEY (id_prestamo) REFERENCES PRESTAMO (id_prestamo),
    CONSTRAINT FK_PAGO_METODO FOREIGN KEY (id_metodo) REFERENCES METODO_PAGO (id_metodo)
);
